apiVersion: skaffold/v1beta11
kind: Config
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: docker.io/stobias123/mineops
  local:
    useBuildkit: true
    push: true
deploy:
  kubectl:
    manifests:
      - manifests/*
profiles:
- name: dev