apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spigot-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spigot
    spec:
      containers:
      - name: spigot-deployment
        image: docker.io/stobias123/mineops